/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:f7a47381-da58-448d-a3eb-c3a9ae9630cb",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_6HSssBiXX",
    "aws_user_pools_web_client_id": "6b9ul9d79d8u9v0aa0hsmv7ldv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ffij4guzwrhwxflsthr3jgljve.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-z6htrmch7jhormxx4u63pwpx5m",
    "aws_user_files_s3_bucket": "cqaenbucket180605-staging",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
